# Generated by Django 2.0.4 on 2018-04-27 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('lang_pro', models.CharField(max_length=500)),
                ('position', models.CharField(max_length=20)),
            ],
        ),
    ]
